name: Node CI

on:
  push:
    branches-ignore:
      - 'dependabot/**'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          - lts/-2
          - lts/-1
          - lts/*
          - latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - name: Install
        run: npm ci
      - name: Node version
        id: version
        run: echo "node-version=$(node -v)" >> $GITHUB_OUTPUT
      - name: Test
        id: test
        run: npm test
        continue-on-error: ${{ matrix.node-version == 'latest' }}
      - name: Fail
        if: ${{ matrix.node-version == 'latest' && steps.test.outcome != 'success' }}
        run: |
          echo "Node.js ${{ matrix.node-version }} (${{ steps.version.outputs.node-version }}) failed"
          exit 0
